### ISSUE TITLE
The compiling error with node 6.9.1

### ISSUE THREAD

**Issue by indigodp** [51Degreesmobi/51degrees.node#28]
Hello!

The compiling error was appeared when i try to install the package.
The os version - ubuntu 16.10
The node version - v.6.9.1

In file included from ../src/pattern/api.cc:33:0:
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:590:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:590:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^~
../node_modules/nan/nan.h:591:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../node_modules/nan/nan.h:596:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:596:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^~
../node_modules/nan/nan.h:601:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:601:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^~
../node_modules/nan/nan.h:602:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../node_modules/nan/nan.h:607:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:607:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^~
../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, 
v8::AccessControl, v8::PropertyAttribute)’:
../node_modules/nan/nan.h:1933:16: warning: ‘bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     , attribute);
                ^
In file included from /home/user/.node-gyp/6.9.1/include/node/v8.h:25:0,
                 from /home/user/.node-gyp/6.9.1/include/node/node.h:42,
                 from ../src/pattern/api.cc:31:
/home/user/.node-gyp/6.9.1/include/node/v8.h:2751:22: note: declared here
                 bool SetAccessor(Local<Name> name,
                      ^
/home/user/.node-gyp/6.9.1/include/node/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/pattern/api.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE PatternParser::Parse(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/pattern/api.cc:108:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (strlen(*v8_input) > maxInputLength) {
       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
pattern.target.mk:100: recipe for target 'Release/obj.target/pattern/src/pattern/api.o' failed
make: *** [Release/obj.target/pattern/src/pattern/api.o] Error 1

**Comment by ben51degrees** [comment]
Hi @indigodp 
This version is no longer being actively maintained. The new version is [here](https://github.com/51degrees/device-detection) and on NPM as "fiftyonedegreescore". The new version compiles and runs on the Ubuntu and node versions you are on, but if you need to use this version then I'd be happy to look into the problem for you.
